apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rewild-app-set
spec:
  generators:
    - git:
        repoURL: https://github.com/arwoosa/rewild.git
        revision: cd
        directories:
        - path: argocd/overlays/*
  template: # used to generate Argo CD Application resources
    metadata:
      name: 'app-rewild-{{path.basename}}'
    spec:
      project: oosa
      source:
        repoURL: https://github.com/arwoosa/rewild.git
        targetRevision: cd
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'oosa-app'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true